name: Magazine Front Workflow

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      
      - name: Docker build
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -t ghcr.io/andrey666berkov/magazinefront/frontmagazin:${{ github.sha }} .

      - name: Docker push
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/andrey666berkov/magazinefront/frontmagazin:${{ github.sha }}

      - name: Deploy to Server
        run: | 
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/deploy/frontend
          docker-compose pull
          docker-compose up -d
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
        
          

