name: Magazine Front Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      
      - name: Docker build
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -t ghcr.io/andrey666berkov/magazinefront/frontmagazin:latest .

      - name: Docker push
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/andrey666berkov/magazinefront/frontmagazin:latest

      - name: Deploy to Server with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PASS }}
          port: 22
          script: |
            set -euo pipefail
            cd /path/to/your/project
            docker-compose pull  
            docker-compose up -d 
            docker ps
            


        
          

